### ISSUE TITLE
Not able to install package

### ISSUE THREAD

**Issue by victorialinden** [benkeser/nlpred#1]
Seems like quantreg is not longer available!

**Comment by benkeser** [comment]
Could you please provide more details? E.g., installing from CRAN? Version of R? Specific error message?

 `quantreg` is not a dependency of this package, so it's hard for me to tell where this error might be originating from.

**Comment by ck37** [comment]
The np package requires quantreg, but everything installed smoothly for me today. Perhaps quantreg got knocked off cran for some time period. I think this issue could be closed.

**Comment by benkeser** [comment]
Thanks!
